### ISSUE TITLE
ERROR: Error while making request to server

### ISSUE THREAD

**Issue by Minirick** [jo1gi/audiobook-dl#45]
**_Please if you can help me, it generates an error_**

![image](https://github.com/jo1gi/audiobook-dl/assets/60492285/3a719c87-f1b3-46fe-8fe8-528435ee41c7)

**Comment by jo1gi** [comment]
I would try running it again. If it keeps not working, I will take a look at it when I get home.

**Comment by Minirick** [comment]
I have kept trying in various ways and it has not left me.

Thank you for being aware of the concerns.
Stay tuned.

**Comment by jo1gi** [comment]
Looks like there is a bug with audiobooks.com. I will try to fix it

**Comment by jo1gi** [comment]
Should be fixed in [9fb3726](https://github.com/jo1gi/audiobook-dl/commit/9fb3726ef66a0252daf6cc9b3000c6f7cc42eead). Could you try it?

**Comment by Minirick** [comment]
Now it throws a new error, it seems to not find the file request_error.txt

![image](https://github.com/jo1gi/audiobook-dl/assets/60492285/9e12cab6-fbf7-4c12-a960-43902ab92877)

**Comment by davetassoni** [comment]
I'm having the same issue

**Comment by jobenaus** [comment]
I can confirm this issue still exists with the latest version from git, installed in a clean virtual environment.
After installing the latest version, I am no longer getting the original error. Instead, the script now fails with a ConnectionResetError: [Errno 54] Connection reset by peer.
The debug traceback shows that this happens specifically when the script tries to run download_cover. The server is actively resetting the connection at that point. I've attached my full debug traceback below.

audiobook-dl --debug --cookie cookies.txt --combine --output-format m4b 'https://www.audiobooks.com/book/stream/514168'
DEBUG audiobook-dl 0.7.3
DEBUG python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]
 INFO Finding compatible source
 INFO Authenticating with audiobooks.com
DEBUG Loading cookies from 'cookies.txt'
DEBUG Downloading result of https://www.audiobooks.com/book/stream/514168
DEBUG user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Ap'
Traceback (most recent call last):
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/Users/johannes/anaconda3/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/Users/johannes/anaconda3/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johannes/anaconda3/bin/audiobook-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/audiobookdl/__main__.py", line 33, in main
    process_url(url, options, config)
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/audiobookdl/__main__.py", line 56, in process_url
    result = source.download(url)
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/audiobookdl/sources/audiobooksdotcom.py", line 33, in download
    cover = self.download_cover(scrape_url),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/audiobookdl/sources/audiobooksdotcom.py", line 50, in download_cover
    return Cover(self.get(cover_url), "jpg")
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/audiobookdl/sources/source/networking.py", line 29, in get
    resp = self._session.get(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johannes/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
